- postman_collection.json
- src/controllers/activity.js
- src/models/Activity.js
- src/routes/activity.js
- src/routes/index.js
- src/validations/activity.js
For each endpoint (GET, GET BY ID, POST, PUT, DELETE:
- Create the routes, controllers and needed JOI validations
- Add them inside postman collection
- Commit and push
> BaSP-MR-14: activity-endpoints

- postman_collection.json
- src/controllers/super-admin.js
- src/index.js
- src/models/Super-admin.js
- src/routes/index.js
- src/routes/postman_collection.json
- src/routes/super-admin.js
- src/validations/super-admin.js
Endpoints created, get, post, put and delete method's created, joi validations added and postman collection modified.
> BaSP-M-10: Super admin endpoints

- src/controllers/activity.js
- src/models/Activity.js
- src/validations/activity.js
- Add relations and populate into resource if needed
- Add async await to activity controller
- Fix code issues
> BaSP-MR-36: ASYNC AWAIT and fix issues

- src/controllers/member.js
- Async/Await functions
- Corrections
> MR-35: ASYNC AWAIT POST/DELETE methods

- src/controllers/class.js
- src/models/Class.js
- src/validations/class.js
- Modified promises to async/await format
- Added ref & populate to activity/trainer
- Fixed smoke test errors
- Added validations to new ref properties
>  BaSP-MR-37: Class REF ASYNC/AWAIT

- src/controllers/activity.js
- src/seeds/activities.js
- src/tests/activities.test.js
Tests with put, post, delete and get.
> BaSP-MR-43: Tests activity

- src/controllers/admin.js
- src/tests/admins.test.js
- src/validations/admin.js
- Tested GET, POST, PUT, DELETE Methods
- Fixed Admin controller
- Changed some JOI Validations
> BaSP-MR-41: Tested Admin Endpoints

- src/models/Super-admin.js
i modify the superAdmin schema
> BaSP-MR-56: fixed superAdmin schema

- src/controllers/trainer.js
- src/tests/trainers.test.js
I solved some issues on Trainers
> BaSP-MR-58: deleted some issues on trainers controllers and tests

- src/controllers/super-admin.js
- src/routes/super-admin.js
- src/tests/super-admin.test.js
fixed the method put  for the validation of existent email and dni.
fixed the name method delete 
added the fixed routes
>  BaSP-MR-57:fixed test super-admin

- src/controllers/admin.js
- src/tests/admins.test.js
Modify the error to "true" on the 200 state of update admin and the message when an admin es updated
> BaSP-MR-59: fix admins controllers

- src/controllers/activity.js
- src/models/Activity.js
Removed a same name validation from the put method and changed the boolean from isActive from false to true
> BaSP - MR-60: Hotfix activites

- src/controllers/class.js
I deleted a validation of hour repeated when you are updating the same class
> BaSP-MR-62: fixed hour bug validation when updated it

- src/controllers/activity.js
- src/controllers/class.js
- src/controllers/member.js
- src/controllers/super-admin.js
- src/controllers/trainer.js
- src/tests/activities.test.js
- src/tests/super-admin.test.js
fixed the validation in update and create for an already existent member,class,superAdmin,trainer or activity
> BaSP:MR 85 validation in update and create

- src/controllers/trainer.js
- src/validations/trainer.js
Fix some error on trainer's validations
> BaSP-MR-82: fix trainer validations

- src/controllers/admin.js
- src/controllers/trainer.js
- src/tests/admins.test.js
Fix the admins update and add a validation for the email and dni if they are used by another user.
> MR-81: Admins update fix

- src/validations/member.js
> BaSP-MR-104:fixed members

- src/controllers/activity.js
- src/controllers/admin.js
- src/controllers/class.js
- src/controllers/member.js
- src/controllers/subscription.js
- src/controllers/super-admin.js
- src/controllers/trainer.js
- src/tests/admins.test.js
- src/tests/members.test.js
- src/tests/super-admin.test.js
- src/validations/admin.js
I fixed validation in admin for the password, corrected the validation for name and last name in admin, and fixed messages in all components for more consistency
> BaSP-MR-119: fixed validation admin, messages for consistency

- src/controllers/activity.js
- src/controllers/class.js
- src/controllers/member.js
- src/controllers/super-admin.js
- src/controllers/trainer.js
- src/tests/activities.test.js
- src/tests/admins.test.js
- src/tests/trainers.test.js
I fixed response status on get methods
> BaSP-MR-125: fix response status on get methods

- src/controllers/activity.js
- src/controllers/admin.js
- src/controllers/class.js
- src/controllers/member.js
- src/controllers/subscription.js
- src/controllers/super-admin.js
- src/controllers/trainer.js
I worked on the messages response in all entities for consistency
> BaSP-MR-117: fix response messages for consistency

- src/controllers/super-admin.js
Fix data when you want to get the list of super admins
> BaSP-MR-124: fix get superAdmins

- jest.setup.js
- src/seeds/classes.js
- src/tests/classes.test.js
- src/validations/class.js
i corrected the validations of the hours in classes so that they are only o'clock hours. i also corrected the stlot so that they are integers.
> BaSP-MR-143:validations classes grid

- src/controllers/member.js
- src/routes/member.js
- src/validations/member.js
A new controller has been added for member login that validates login with ID and email. 
The path to this new controller and its corresponding validations are created.
> BaSP-MR-145:  add a login for member

- src/models/Member.js
I fixed default value on "isActive" member schema
> MR-147: fix member schema

- src/controllers/subscription.js
I added a validatión in subscription, now you cannot add more subscriptions to a single class than the class slots
> BaSP-MR-144: added a validatión when the slots are full

- src/controllers/admin.js
- src/tests/admins.test.js
I fixed the admins controller when update with no changes
> BaSP-MR- 154: fix admins when updated

- src/controllers/member.js
Fixed bugs on controller loginMember.
> BaSP-MR-155: fixed bugs

- package-lock.json
- package.json
- src/controllers/subscription.js
- src/seeds/subscriptions.js
- src/tests/subscriptions.test.js
I added a validation that allows subscribing to a class only if the class starts at least one minute later and at most six days earlier, and also validate the date day must match with the class day
> BaSP-MR-150: Add a date validation

- src/controllers/subscription.js
- src/seeds/activities.js
- src/seeds/classes.js
- src/seeds/members.js
- src/seeds/trainers.js
- src/tests/subscriptions.test.js
i fixed the test in subscription
> BaSP-MR-156: fixed test subscription

- src/controllers/subscription.js
- src/routes/subscription.js
I added a deleteMany function. this delete all old subscription so you can clean all the old slots
> BaSP-MR-139: added a delete all old subscription

- src/controllers/subscription.js
- src/tests/subscriptions.test.js
Fix date validations on subscriptions
> FIX-MR-171: fix date validations

- src/routes/activity.js
- src/routes/admin.js
- src/routes/class.js
- src/routes/member.js
- src/routes/subscription.js
- src/routes/trainer.js
I commented some lines because the QA can't work if I didn't do that
> BaSP-MR-186: fix some code for the QA

- package.json
> MR-161: modified package.json

- src/app.js
- src/controllers/member.js
- src/routes/activity.js
- src/routes/member.js
- src/routes/subscription.js
- src/validations/member.js
I did authentication for member entity
> BaSP-MR-166: member authentication

- src/controllers/trainer.js
- src/routes/activity.js
- src/routes/member.js
- src/routes/trainer.js
i made the authentication for trainers
> BaSP-MR-165:auth trainers

- package-lock.json
- src/controllers/admin.js
- src/routes/activity.js
- src/routes/admin.js
- src/routes/auth.js
- src/routes/class.js
- src/routes/member.js
- src/routes/subscription.js
- src/routes/trainer.js
Authentication and routes for admins
> BaSP-MR-164: Auth Admin server

- src/validations/member.js
I fixed the birth date validation on the sign up for members
> BaSP-MR-197: fix member validation birthdate

- src/controllers/admin.js
- src/controllers/member.js
- src/controllers/super-admin.js
- src/controllers/trainer.js
I added the delete firebase database when you try to delete a member, trainer, admin, or superadmin
> BaSP-MR-202: Delete firebase user

- src/controllers/auth.js
- src/routes/auth.js
fix routes and controllers for auth
> BaSP-MR-190: fix routes and controllers for auth

- package-lock.json
- package.json
- src/controllers/chat.js
- src/routes/chat.js
- src/routes/index.js
> MR-178: implement chat GPT

- src/routes/subscription.js
I changed subscription validations
> BaSP-MR-216: Changed subscriptions validation

- src/controllers/class.js
- src/controllers/subscription.js
- src/routes/class.js
if a trainer, or activity is deleted the class will be automatically deleted, if a class or a member is deleted the subscriptions who match anyone of them will be automatically deleted
> BaSP-MR-218: automatically deleted subsctiption and classes

- src/controllers/class.js
- src/controllers/subscription.js
I added a validation to deleteMany when a trainer or a member is inactive
> BaSP-MR-230: Is active validation
